<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <!-- Existing Assets -->
    <AvaloniaResource Include="Assets\**\*.*" />

  </ItemGroup>

  <ItemGroup>
    <!-- Avalonia Dependencies -->
    <PackageReference Include="Avalonia" Version="11.3.7" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.7" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.7" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.7" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.7">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>